# Generated by Django 5.2.16 on 2026-07-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(verbose_name="Название урока")),
                (
                    "description",
                    models.CharField(blank=True, default="Добавьте опиcание", verbose_name="Описание урока"),
                ),
                ("preview", models.ImageField(blank=True, null=True, upload_to="lesson/", verbose_name="Фотография")),
                ("video_link", models.CharField(verbose_name="Сылка на видео")),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(verbose_name="Название курса")),
                ("preview", models.ImageField(blank=True, null=True, upload_to="couse/", verbose_name="Фотография")),
                ("description", models.CharField(blank=True, default="Без опиcания", verbose_name="Описание курса")),
                (
                    "lessons",
                    models.ManyToManyField(
                        blank=True, null=True, to="syllabus.lesson", verbose_name="Получатели рассылки"
                    ),
                ),
            ],
        ),
    ]
