# Generated by Django 5.2.16 on 2026-07-26 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabus", "0002_alter_course_lessons"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name="Ученики"),
        ),
        migrations.AlterField(
            model_name="course",
            name="lessons",
            field=models.ManyToManyField(blank=True, to="syllabus.lesson", verbose_name="Уроки курса"),
        ),
    ]
