# Generated by Django 5.2.16 on 2026-07-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="lessons",
            field=models.ManyToManyField(blank=True, to="syllabus.lesson", verbose_name="Получатели рассылки"),
        ),
    ]
