# Generated by Django 5.2.16 on 2026-07-26 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabus", "0003_course_students_alter_course_lessons"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Ученики"),
        ),
    ]
